const API_SERVER = "https://localhost:7150";
const RETURN_URL = process.env.NEXT_PUBLIC_RETURN_URL;
const ZEGO_APP_ID = Number(process.env.NEXT_PUBLIC_ZEGO_APP_ID);
const ZEGO_SERVER_SECRET = process.env.NEXT_PUBLIC_ZEGO_SERVER_SECRET || "";

const USER_INFO = "_user_info";
const ACCESS_TOKEN = "_access_token";
const CLIENT_ID_GOOGLE = process.env.NEXT_PUBLIC_CLIENT_ID_GOOGLE;
const REDIRECT_URL_GOOGLE = process.env.NEXT_PUBLIC_REDIRECT_URL_GOOGLE || "";
const DOMAIN_GOOGLE = process.env.NEXT_PUBLIC_DOMAIN_GOOGLE;
const ENPOINT_URL_GOOGLE = `https://${DOMAIN_GOOGLE}/oauth2/authorize?response_type=code&identity_provider=Google&client_id=${CLIENT_ID_GOOGLE}&redirect_uri=${REDIRECT_URL_GOOGLE}`;

const FIREBASE_API_KEY = process.env.NEXT_PUBLIC_FIREBASE_API_KEY;
const FIREBASE_AUTH_DOMAIN = process.env.NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN;
const FIREBASE_PROJECT_ID = process.env.NEXT_PUBLIC_FIREBASE_PROJECT_ID;
const FIREBASE_MESSAGING_SENDER_ID = process.env.NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID;
const FIREBASE_APP_ID = process.env.NEXT_PUBLIC_FIREBASE_APP_ID;
const FIREBASE_MEASUREMENT_ID = process.env.NEXT_PUBLIC_FIREBASE_MEASUREMENT_ID;
const FIREBASE_STORAGE_BUCKET = process.env.NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET;

const LOCALE = "_locale";

const constants = {
  API_SERVER,
  USER_INFO,
  ACCESS_TOKEN,
  FIREBASE_API_KEY,
  FIREBASE_AUTH_DOMAIN,
  FIREBASE_PROJECT_ID,
  FIREBASE_MESSAGING_SENDER_ID,
  FIREBASE_APP_ID,
  FIREBASE_MEASUREMENT_ID,
  FIREBASE_STORAGE_BUCKET,
  RETURN_URL,
  REDIRECT_URL_GOOGLE,
  ENPOINT_URL_GOOGLE,
  LOCALE,
  ZEGO_APP_ID,
  ZEGO_SERVER_SECRET
};

export default constants;
